#!/bin/sh
./configure --host=arm-eabi --without-zlib --prefix=$DEVKITARM \
CFLAGS="-g -Wall -O2 -march=armv5te -mtune=arm946e-s -fomit-frame-pointer -ffast-math -mthumb -mthumb-interwork -I/opt/devkitpro/libnds/include -I/opt/devkitpro/libnds/include -I/home/thomas/data/programming/nds/test/build -DARM9" \
CXXFLAGS="$CFLAGS -fno-rtti -fno-exceptions" \
LDFLAGS="-specs=ds_arm9.specs /opt/devkitpro/libnds/lib/libnds9d.a"

